from django.db import migrations
from decimal import Decimal


def seed_sports_items(apps, schema_editor):
    Item = apps.get_model('core', 'Item')
    
    sports_items = [
        # Football / Soccer items
        {
            'title': 'Professional Soccer Ball',
            'price': Decimal('3500.00'),
            'discount_price': Decimal('2999.00'),
            'category': 'FB',
            'label': 'S',
            'slug': 'professional-soccer-ball',
            'description': 'Official size 5 soccer ball with premium synthetic leather. Perfect for match play and training.',
            'brand': 'Nike',
            'stock': 25,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Soccer Cleats Premium',
            'price': Decimal('8999.00'),
            'discount_price': Decimal('6999.00'),
            'category': 'FB',
            'label': 'D',
            'slug': 'soccer-cleats-premium',
            'description': 'Lightweight football boots with responsive cushioning for enhanced performance.',
            'brand': 'Adidas',
            'stock': 15,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Football Training Cones Set',
            'price': Decimal('1200.00'),
            'discount_price': None,
            'category': 'FB',
            'label': 'P',
            'slug': 'football-training-cones',
            'description': 'Set of 10 training cones in bright yellow. Essential for agility drills.',
            'brand': 'Generic',
            'stock': 40,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Shin Guard Protection',
            'price': Decimal('2500.00'),
            'discount_price': None,
            'category': 'FB',
            'label': 'P',
            'slug': 'shin-guard-protection',
            'description': 'Padded shin guards with ankle protection for safe play.',
            'brand': 'Puma',
            'stock': 30,
            'featured': False,
            'active': True,
        },
        
        # Basketball items
        {
            'title': 'Pro Basketball',
            'price': Decimal('4500.00'),
            'discount_price': Decimal('3799.00'),
            'category': 'BK',
            'label': 'S',
            'slug': 'pro-basketball',
            'description': 'Regulation size basketball with superior grip and bounce control.',
            'brand': 'Spalding',
            'stock': 20,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Basketball Shoes High Top',
            'price': Decimal('9999.00'),
            'discount_price': Decimal('7999.00'),
            'category': 'BK',
            'label': 'D',
            'slug': 'basketball-shoes-high-top',
            'description': 'High-performance basketball shoes with ankle support and cushioning.',
            'brand': 'Jordan',
            'stock': 18,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Basketball Backboard',
            'price': Decimal('12000.00'),
            'discount_price': Decimal('9999.00'),
            'category': 'BK',
            'label': 'S',
            'slug': 'basketball-backboard',
            'description': 'Portable basketball backboard with adjustable height.',
            'brand': 'Spalding',
            'stock': 8,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Basketball Socks Crew',
            'price': Decimal('800.00'),
            'discount_price': None,
            'category': 'BK',
            'label': 'P',
            'slug': 'basketball-socks-crew',
            'description': 'Moisture-wicking crew socks designed for basketball players.',
            'brand': 'Nike',
            'stock': 50,
            'featured': False,
            'active': True,
        },
        
        # Tennis & Racket Sports
        {
            'title': 'Professional Tennis Racket',
            'price': Decimal('6500.00'),
            'discount_price': Decimal('4999.00'),
            'category': 'TN',
            'label': 'S',
            'slug': 'professional-tennis-racket',
            'description': 'Lightweight tennis racket with graphite frame for maximum power.',
            'brand': 'Wilson',
            'stock': 12,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Tennis Balls Can (3pcs)',
            'price': Decimal('1500.00'),
            'discount_price': None,
            'category': 'TN',
            'label': 'P',
            'slug': 'tennis-balls-can',
            'description': 'High-quality tennis balls in pressurized can for consistent play.',
            'brand': 'Wilson',
            'stock': 35,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Badminton Racket Pair',
            'price': Decimal('3500.00'),
            'discount_price': Decimal('2799.00'),
            'category': 'TN',
            'label': 'D',
            'slug': 'badminton-racket-pair',
            'description': 'Professional-grade badminton rackets with carrying bag.',
            'brand': 'Yonex',
            'stock': 20,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Squash Racket',
            'price': Decimal('5000.00'),
            'discount_price': Decimal('3999.00'),
            'category': 'TN',
            'label': 'S',
            'slug': 'squash-racket',
            'description': 'Professional squash racket with perfect balance and control.',
            'brand': 'Dunlop',
            'stock': 10,
            'featured': False,
            'active': True,
        },
        
        # Running & Fitness
        {
            'title': 'Running Shoes Pro',
            'price': Decimal('7999.00'),
            'discount_price': Decimal('5999.00'),
            'category': 'RN',
            'label': 'S',
            'slug': 'running-shoes-pro',
            'description': 'Cushioned running shoes for road and track with responsive foam.',
            'brand': 'Nike',
            'stock': 28,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Yoga Mat Premium',
            'price': Decimal('2500.00'),
            'discount_price': None,
            'category': 'RN',
            'label': 'P',
            'slug': 'yoga-mat-premium',
            'description': 'Non-slip yoga mat with carrying strap and thick padding.',
            'brand': 'Generic',
            'stock': 30,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Dumbbell Set (10kg)',
            'price': Decimal('4500.00'),
            'discount_price': Decimal('3999.00'),
            'category': 'RN',
            'label': 'D',
            'slug': 'dumbbell-set-10kg',
            'description': 'Adjustable dumbbell set for home and gym workouts.',
            'brand': 'Generic',
            'stock': 15,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Sports Water Bottle',
            'price': Decimal('1200.00'),
            'discount_price': None,
            'category': 'RN',
            'label': 'P',
            'slug': 'sports-water-bottle',
            'description': 'Insulated water bottle keeps drinks cold for up to 24 hours.',
            'brand': 'Hydro Flask',
            'stock': 60,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Jump Rope Speed',
            'price': Decimal('800.00'),
            'discount_price': None,
            'category': 'RN',
            'label': 'P',
            'slug': 'jump-rope-speed',
            'description': 'Lightweight speed jump rope with ball bearings and ergonomic handles.',
            'brand': 'Generic',
            'stock': 45,
            'featured': False,
            'active': True,
        },
        
        # Outdoor & Hiking
        {
            'title': 'Hiking Backpack 50L',
            'price': Decimal('8500.00'),
            'discount_price': Decimal('6999.00'),
            'category': 'OW',
            'label': 'S',
            'slug': 'hiking-backpack-50l',
            'description': 'Durable hiking backpack with multiple compartments and rain cover.',
            'brand': 'Osprey',
            'stock': 18,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Camping Tent 2 Person',
            'price': Decimal('6500.00'),
            'discount_price': Decimal('4999.00'),
            'category': 'OW',
            'label': 'S',
            'slug': 'camping-tent-2-person',
            'description': 'Waterproof camping tent with ventilation and easy setup.',
            'brand': 'Coleman',
            'stock': 12,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Hiking Boots Waterproof',
            'price': Decimal('7500.00'),
            'discount_price': Decimal('5999.00'),
            'category': 'OW',
            'label': 'D',
            'slug': 'hiking-boots-waterproof',
            'description': 'Premium waterproof hiking boots with ankle support.',
            'brand': 'Salomon',
            'stock': 16,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Sleeping Bag Summer',
            'price': Decimal('3500.00'),
            'discount_price': Decimal('2799.00'),
            'category': 'OW',
            'label': 'D',
            'slug': 'sleeping-bag-summer',
            'description': 'Lightweight sleeping bag suitable for summer camping.',
            'brand': 'Coleman',
            'stock': 20,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Portable Camping Stove',
            'price': Decimal('2500.00'),
            'discount_price': None,
            'category': 'OW',
            'label': 'P',
            'slug': 'portable-camping-stove',
            'description': 'Compact camping stove for cooking outdoors.',
            'brand': 'Generic',
            'stock': 25,
            'featured': False,
            'active': True,
        },
        
        # Sports Apparel & Accessories
        {
            'title': 'Sports T-Shirt Pro',
            'price': Decimal('1500.00'),
            'discount_price': Decimal('999.00'),
            'category': 'AP',
            'label': 'D',
            'slug': 'sports-tshirt-pro',
            'description': 'Breathable moisture-wicking sports t-shirt for all activities.',
            'brand': 'Nike',
            'stock': 60,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Sports Shorts Quick Dry',
            'price': Decimal('2000.00'),
            'discount_price': Decimal('1299.00'),
            'category': 'AP',
            'label': 'D',
            'slug': 'sports-shorts-quick-dry',
            'description': 'Quick-dry shorts with pockets and comfortable fit.',
            'brand': 'Adidas',
            'stock': 50,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Sports Watch Smartband',
            'price': Decimal('5999.00'),
            'discount_price': Decimal('3999.00'),
            'category': 'AP',
            'label': 'S',
            'slug': 'sports-watch-smartband',
            'description': 'Fitness smartwatch with heart rate monitor and GPS.',
            'brand': 'Garmin',
            'stock': 22,
            'featured': True,
            'active': True,
        },
        {
            'title': 'Sports Cap Baseball',
            'price': Decimal('800.00'),
            'discount_price': None,
            'category': 'AP',
            'label': 'P',
            'slug': 'sports-cap-baseball',
            'description': 'Classic baseball cap with adjustable strap.',
            'brand': 'Generic',
            'stock': 70,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Gym Bag Duffel',
            'price': Decimal('3000.00'),
            'discount_price': Decimal('1999.00'),
            'category': 'AP',
            'label': 'D',
            'slug': 'gym-bag-duffel',
            'description': 'Spacious gym duffel bag with shoe compartment.',
            'brand': 'Generic',
            'stock': 35,
            'featured': False,
            'active': True,
        },
        {
            'title': 'Sports Gloves Training',
            'price': Decimal('2500.00'),
            'discount_price': None,
            'category': 'AP',
            'label': 'P',
            'slug': 'sports-gloves-training',
            'description': 'Padded training gloves for boxing and fitness.',
            'brand': 'Generic',
            'stock': 40,
            'featured': False,
            'active': True,
        },
    ]
    
    for item_data in sports_items:
        Item.objects.get_or_create(slug=item_data['slug'], defaults=item_data)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_address_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_sports_items),
    ]
