# Generated by Django 6.0.6 on 2026-09-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_seed_hero_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('esewa', 'eSewa')], max_length=10),
        ),
    ]
